### ISSUE TITLE
vmc push --no-start throws a ruby error

### ISSUE THREAD

**Issue by mminella** [cloudfoundry-attic/vmc#67] opened 2013-03-21 03:09 UTC
I am using vmc 0.5.1.rc4.  When I attempt to do a vmc push --no-start, I am receiving the following error (using the same application from when I logged issue 65):

``` bash
Uploading part... FAILED
Upload failed. Try again with 'vmc push'.
NoMethodError: undefined method `each' for nil:NilClass
For more information, see ~/.vmc/crash
```

Below is the resulting crash report:

```
Time of crash:
  2013-03-20 22:01:22 -0500

NoMethodError: undefined method `each' for nil:NilClass

cfoundry-0.5.3.rc5/lib/cfoundry/upload_helpers.rb:193:in `make_fingerprints'
cfoundry-0.5.3.rc5/lib/cfoundry/upload_helpers.rb:152:in `determine_resources'
cfoundry-0.5.3.rc5/lib/cfoundry/upload_helpers.rb:44:in `upload'
vmc-0.5.1.rc4/lib/vmc/cli/app/push.rb:90:in `block in upload_app'
interact-0.5.2/lib/interact/progress.rb:98:in `with_progress'
vmc-0.5.1.rc4/lib/vmc/cli/app/push.rb:89:in `upload_app'
vmc-0.5.1.rc4/lib/vmc/cli/app/push.rb:69:in `setup_new_app'
vmc-0.5.1.rc4/lib/vmc/cli/app/push.rb:52:in `push'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in `block in invoke'
manifests-vmc-plugin-0.6.3.rc2/lib/manifests-vmc-plugin/plugin.rb:142:in `call'
manifests-vmc-plugin-0.6.3.rc2/lib/manifests-vmc-plugin/plugin.rb:142:in `block in create_and_save_manifest'
mothership-0.5.1/lib/mothership/callbacks.rb:74:in `with_filters'
manifests-vmc-plugin-0.6.3.rc2/lib/manifests-vmc-plugin/plugin.rb:140:in `create_and_save_manifest'
manifests-vmc-plugin-0.6.3.rc2/lib/manifests-vmc-plugin/plugin.rb:80:in `wrap_push'
manifests-vmc-plugin-0.6.3.rc2/lib/manifests-vmc-plugin/plugin.rb:29:in `block in <class:ManifestsPlugin>'
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in `block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
vmc-0.5.1.rc4/lib/vmc/cli.rb:150:in `block (2 levels) in execute'
vmc-0.5.1.rc4/lib/vmc/cli.rb:161:in `save_token_if_it_changes'
vmc-0.5.1.rc4/lib/vmc/cli.rb:149:in `block in execute'
vmc-0.5.1.rc4/lib/vmc/cli.rb:100:in `wrap_errors'
vmc-0.5.1.rc4/lib/vmc/cli.rb:145:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
vmc-0.5.1.rc4/bin/vmc:11:in `<top (required)>'
ruby-2.0.0-p0/bin/vmc:23:in `load'
ruby-2.0.0-p0/bin/vmc:23:in `<main>'
ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by cf-frontend** [comment] 2013-03-21 21:44
We were unable to reproduce this problem but we're pretty sure we've found what was causing this problem. There is a new pre-release out (v0.5.1.rc5) that has a fix for this. Please don't hesitate to reopen the issue if it is still present.
- Chris

**Closed as completed by cf-frontend** 2013-03-21 21:44 UTC

**Comment by mminella** [comment] 2013-03-22 22:38
That fixed the issue.  Thanks for all your support!
